#!/usr/bin/env python3
"""
Task #011.17: Universal 4-Node SSH Mesh Setup
Purpose: Deploy SSH public keys to all remote nodes (GTW, HUB, GPU)
Protocol: v2.2 (Docs-as-Code)

Features:
- Generates local SSH key pair if missing
- Handles platform differences (Windows vs Linux)
- Interactive password authentication via Paramiko
- Batch deployment to multiple remote nodes
- Error handling and rollback

Dependencies:
- paramiko (SSH library)
- cryptography (for key operations)
"""

import os
import sys
import subprocess
from pathlib import Path
from getpass import getpass
import paramiko
from paramiko import SSHClient, AutoAddPolicy
import stat

# Color codes
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
CYAN = "\033[96m"
RESET = "\033[0m"

# Paths
HOME = Path.home()
SSH_DIR = HOME / ".ssh"
PRIVATE_KEY_PATH = SSH_DIR / "id_rsa"
PUBLIC_KEY_PATH = SSH_DIR / "id_rsa.pub"
CONFIG_PATH = SSH_DIR / "config"

# Remote nodes configuration
REMOTE_NODES = {
    "gtw": {
        "hostname": "172.19.141.255",
        "user": "Administrator",
        "os": "Windows",
        "ssh_dir": r"C:\Users\Administrator\.ssh",
    },
    "hub": {
        "hostname": "172.19.141.254",
        "user": "root",
        "os": "Linux",
        "ssh_dir": "/root/.ssh",
    },
    "gpu": {
        "hostname": "www.guangzhoupeak.com",
        "user": "root",
        "os": "Linux",
        "ssh_dir": "/root/.ssh",
    },
}


def print_header(title, subtitle=""):
    """Print formatted section header."""
    print(f"\n{CYAN}{'='*80}{RESET}")
    print(f"{CYAN}  {title}{RESET}")
    if subtitle:
        print(f"{CYAN}  {subtitle}{RESET}")
    print(f"{CYAN}{'='*80}{RESET}\n")


def check_status(name, status, detail="", error=""):
    """Print formatted status check."""
    symbol = f"{GREEN}✅{RESET}" if status else f"{RED}❌{RESET}"
    detail_str = f"  [{detail}]" if detail else ""
    if error:
        print(f"  {symbol} {name:<50} {detail_str}")
        print(f"     {RED}Error: {error}{RESET}")
    else:
        print(f"  {symbol} {name:<50} {detail_str}")
    return status


def step(num, description):
    """Print step number."""
    print(f"\n{BLUE}[Step {num}]{RESET} {description}")


def generate_ssh_key():
    """Generate SSH key pair if missing."""
    step(1, "Generate SSH Key Pair")

    if PRIVATE_KEY_PATH.exists():
        check_status("SSH key exists", True, str(PRIVATE_KEY_PATH))
        return True

    print(f"  Generating new SSH key pair...")

    try:
        # Generate RSA key using ssh-keygen
        subprocess.run(
            [
                "ssh-keygen",
                "-t", "rsa",
                "-b", "4096",
                "-f", str(PRIVATE_KEY_PATH),
                "-N", "",  # No passphrase for automation
                "-C", f"mt5-mesh-{os.getenv('USER', 'root')}@172.19.141.250"
            ],
            check=True,
            capture_output=True,
            timeout=10
        )

        # Set permissions
        os.chmod(PRIVATE_KEY_PATH, 0o600)
        os.chmod(PUBLIC_KEY_PATH, 0o644)

        check_status("SSH key generated", True, f"4096-bit RSA")
        return True

    except subprocess.CalledProcessError as e:
        check_status("SSH key generation", False, "", str(e))
        return False
    except Exception as e:
        check_status("SSH key generation", False, "", str(e))
        return False


def read_public_key():
    """Read public key from file."""
    step(2, "Read Public Key")

    if not PUBLIC_KEY_PATH.exists():
        check_status("Public key exists", False, "", "Not found - run key generation first")
        return None

    try:
        with open(PUBLIC_KEY_PATH, 'r') as f:
            pub_key = f.read().strip()

        # Extract key fingerprint
        if pub_key.startswith("ssh-rsa"):
            fingerprint = pub_key.split()[1][:16]
        else:
            fingerprint = "unknown"

        check_status("Public key readable", True, f"Fingerprint: {fingerprint}...")
        return pub_key

    except Exception as e:
        check_status("Public key read", False, "", str(e))
        return None


def generate_ssh_config():
    """Generate SSH config file."""
    step(3, "Generate SSH Config")

    config_content = """# SSH Mesh Configuration (auto-generated by ops_universal_key_setup.py)
# 4-Node Distributed Trading Infrastructure

Host gtw
    HostName 172.19.141.255
    User Administrator
    IdentityFile ~/.ssh/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    ConnectTimeout 10
    ServerAliveInterval 60
    ServerAliveCountMax 5

Host hub
    HostName 172.19.141.254
    User root
    IdentityFile ~/.ssh/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    ConnectTimeout 10
    ServerAliveInterval 60
    ServerAliveCountMax 5

Host gpu
    HostName www.guangzhoupeak.com
    User root
    IdentityFile ~/.ssh/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    ConnectTimeout 30
    ServerAliveInterval 60
    ServerAliveCountMax 5

# Global settings
Host *
    IdentityFile ~/.ssh/id_rsa
    IdentityFile ~/.ssh/id_ed25519
    AddKeysToAgent yes
    IgnoreUnknown UseKeychain
    UseKeychain yes
"""

    # Create .ssh directory if needed
    SSH_DIR.mkdir(mode=0o700, exist_ok=True)

    # Write config file
    try:
        with open(CONFIG_PATH, 'w') as f:
            f.write(config_content)

        # Set permissions
        os.chmod(CONFIG_PATH, 0o600)

        check_status("SSH config created", True, str(CONFIG_PATH))
        return True

    except Exception as e:
        check_status("SSH config creation", False, "", str(e))
        return False


def deploy_key_to_node(node_name, node_config, public_key):
    """Deploy public key to remote node."""
    step(4, f"Deploy Key to {node_name.upper()} ({node_config['hostname']})")

    hostname = node_config["hostname"]
    user = node_config["user"]
    os_type = node_config["os"]
    ssh_dir = node_config["ssh_dir"]

    # Prompt for password
    password = getpass(f"  Enter password for {user}@{hostname}: ")

    if not password:
        check_status(f"Authentication {node_name}", False, "", "No password provided")
        return False

    try:
        # Create SSH client
        client = SSHClient()
        client.set_missing_host_key_policy(AutoAddPolicy())

        # Connect
        print(f"  Connecting to {hostname}...")
        client.connect(
            hostname=hostname,
            username=user,
            password=password,
            timeout=10,
            look_for_keys=False,
            allow_agent=False
        )
        check_status(f"SSH connection to {node_name}", True, f"{user}@{hostname}")

        # Prepare commands based on OS
        if os_type == "Windows":
            # Windows PowerShell commands
            mkdir_cmd = f'if not exist "{ssh_dir}" mkdir "{ssh_dir}"'
            append_cmd = f'echo {public_key} >> "{ssh_dir}\\authorized_keys"'
            chmod_cmd = ""  # Windows doesn't use Unix perms
            full_cmd = f'{mkdir_cmd} && {append_cmd}'
        else:
            # Linux bash commands
            mkdir_cmd = f"mkdir -p {ssh_dir}"
            append_cmd = f"echo '{public_key}' >> {ssh_dir}/authorized_keys"
            chmod_cmd = f"chmod 600 {ssh_dir}/authorized_keys"
            full_cmd = f'{mkdir_cmd} && {append_cmd} && {chmod_cmd}'

        # Execute deployment command
        print(f"  Deploying public key to {ssh_dir}...")
        stdin, stdout, stderr = client.exec_command(full_cmd)
        stdout.channel.recv_exit_status()
        error_output = stderr.read().decode().strip()

        if error_output and "already exists" not in error_output:
            check_status(f"Key deployment to {node_name}", False, "", error_output)
            client.close()
            return False

        # Verify deployment
        verify_cmd = f"cat {ssh_dir}/authorized_keys" if os_type == "Linux" else f'type "{ssh_dir}\\authorized_keys"'
        stdin, stdout, stderr = client.exec_command(verify_cmd)
        verify_output = stdout.read().decode().strip()

        if public_key[:20] in verify_output:
            check_status(f"Key deployed to {node_name}", True, f"authorized_keys updated")
            client.close()
            return True
        else:
            check_status(f"Key verification on {node_name}", False, "", "Key not found in authorized_keys")
            client.close()
            return False

    except paramiko.AuthenticationException as e:
        check_status(f"Authentication {node_name}", False, "", "Invalid password or authentication failed")
        return False
    except paramiko.SSHException as e:
        check_status(f"SSH connection {node_name}", False, "", str(e))
        return False
    except Exception as e:
        check_status(f"Key deployment {node_name}", False, "", str(e))
        return False


def main():
    """Execute SSH mesh setup."""
    print(f"\n{CYAN}{'='*80}{RESET}")
    print(f"{CYAN}  TASK #011.17: UNIVERSAL SSH MESH KEY SETUP{RESET}")
    print(f"{CYAN}  4-Node Distributed Infrastructure{RESET}")
    print(f"{CYAN}{'='*80}{RESET}\n")

    # Step 1: Generate key
    if not generate_ssh_key():
        print(f"\n{RED}❌ Failed to generate SSH key{RESET}\n")
        return 1

    # Step 2: Read public key
    public_key = read_public_key()
    if not public_key:
        print(f"\n{RED}❌ Failed to read public key{RESET}\n")
        return 1

    # Step 3: Generate config
    if not generate_ssh_config():
        print(f"\n{RED}❌ Failed to generate SSH config{RESET}\n")
        return 1

    # Step 4: Deploy to all nodes
    print(f"\n{YELLOW}⚠️  Interactive password authentication required for each node{RESET}")
    print(f"{YELLOW}    (3 passwords will be prompted)\n{RESET}")

    deployed_nodes = 0
    total_nodes = len(REMOTE_NODES)

    for node_name, node_config in REMOTE_NODES.items():
        if deploy_key_to_node(node_name, node_config, public_key):
            deployed_nodes += 1
        print()

    # Summary
    print_header("DEPLOYMENT SUMMARY")
    print(f"  Total Nodes: {total_nodes}")
    print(f"  Successfully Deployed: {GREEN}{deployed_nodes}{RESET}")
    print(f"  Failed: {RED if deployed_nodes < total_nodes else GREEN}{total_nodes - deployed_nodes}{RESET}")

    if deployed_nodes == total_nodes:
        print(f"\n  {GREEN}✅ SSH mesh setup complete!{RESET}")
        print(f"  {GREEN}All nodes are configured for password-less SSH access.{RESET}")
        print(f"\n  {GREEN}You can now run:{RESET}")
        print(f"    • ssh gtw              (connect to Gateway)")
        print(f"    • ssh hub              (connect to Hub)")
        print(f"    • ssh gpu              (connect to GPU)")
        print(f"    • ssh gtw 'command'    (run command on Gateway)")
        print(f"\n  {GREEN}Next step: Run verify_ssh_mesh.py to validate connectivity.{RESET}\n")
        return 0
    else:
        print(f"\n  {YELLOW}⚠️  Some nodes failed to deploy.{RESET}")
        print(f"  {YELLOW}Please check the errors above and retry.{RESET}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
